name: "Publish builder image"

on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
      - 'ui/**'
      - 'vpn/**'
      - 'build.sh'

permissions:
  packages: write

jobs:
  publish_images:
    name: 'Publish controller images'
    runs-on: ubuntu-latest
    env:
      IMAGETAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - id: build
        run: |
          # Build the controller images
          bash build.sh
      - id: publish
        run: |
          # Publish the branch
          trap 'buildah logout ghcr.io' EXIT
          buildah login -u ${{ github.actor }} --password-stdin ghcr.io <<<"${{ secrets.GITHUB_TOKEN }}"
          images=(${{ steps.build.outputs.images }})
          urls=""
          for image in "${images[@]}" ; do
            buildah push $image docker://${image}:${IMAGETAG:?}
            if [[ "${IMAGETAG}" == "main" || "${IMAGETAG}" == "master" ]]; then
                buildah push $image docker://${image}:latest
            fi
            urls="${image}:${IMAGETAG} "$'\n'"${urls}"
          done
          echo "::notice title=Image URLs::${urls}"
